### ISSUE TITLE
Problems on Mac

### ISSUE THREAD

**Issue by jbradt** [Lunderberg/magic_cpp_makefile#3]
Two problems occur under OS X, probably due to the non-GNU version of `ld` provided by Apple.

1.`make` looks for the path `lib` and fails if it doesn't exist. 
2. The `ld` flag `--no-as-needed` does not exist on Mac.

Removing the flags `-Llib` and `--no-as-needed` from `LDFLAGS_EXTRA` in `default.inc` makes it compile successfully.

The system I had this problem on was running OS X 10.11.3 El Capitan. The compiler was Clang 3.7.0 (a vanilla version from llvm.org, not the Apple-default version).

**Comment by Lunderberg** [comment]
Notes to self: With GNU's `ld`, there is no check whether `lib` exists when being passed `-Llib`.  In Apple's `ld`, there is.

**Comment by Lunderberg** [comment]
A bit late, but the makefile is now compatible with OSX.  The `--no-as-needed` flag was removed, and there were some incompatible flags to `cp`.  For the `-Llib` flag, it only gives a warning, not an error, so I'm not going to worry about that one for now.

Also, there's now continuous integration running at https://travis-ci.org/Lunderberg/magic_cpp_makefile, which tests on OSX 10.10, 10.11, and 10.12 with each each commit, with should help me avoid accidentally breaking support for OSX.
